feat: add individual cronjob enable flags
Sefaria/Sefaria-Project pull request #1309
Opened 2023-03-27 10:02 UTC by paddatrapper

2023-03-27 10:42 UTC, BrendanGalloway requested changes

2023-03-27 10:42 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/cronjob/daily-email-notifications.yaml
> +{{- if .Values.conJobs.dailyEmailNotifications.enabled }}
cron

2023-04-19 08:23 UTC, edamboritz approved these changes

2023-04-19 08:27 UTC, BrendanGalloway approved these changes

2023-04-19 08:27 UTC, merged