ci: use wif for GCP authentication
Sefaria/Sefaria-Project pull request #1372
Opened 2023-05-17 07:57 UTC by paddatrapper

2023-05-17 08:30 UTC, BrendanGalloway requested changes

2023-05-17 08:30 UTC, BrendanGalloway commented on .github/workflows/continuous.yaml
>        - name: Authenticate GHA Runner to GCP
Need to remove json credentials here too

2023-05-17 09:28 UTC, BrendanGalloway approved these changes

2023-05-22 11:06 UTC, BrendanGalloway approved these changes

2023-05-22 11:19 UTC, edamboritz approved these changes

2023-05-22 11:19 UTC, merged