Redirection to Strapi endpoints for mobile app users
Sefaria/Sefaria-Project pull request #1641
Opened 2023-09-19 02:40 UTC by relyks

Story details: https://app.shortcut.com/sefaria/story/19579

### Forewarning
This is likely wrong lol. I only tested the redirection part in an example Nginx Docker container on my local. I don't know the correct location or way to reference the secret environment variable used to define `STRAPI_LOCATION`. Since it's only for production, the port shouldn't be necessary.

## Background
I integrated Strapi CMS into Sefaria's codebase. It's currently used on the web interface to serve the content for modals, banners, and sidebar ads. The mobile app currently uses static JSON files for that content which the site needs to redeployed every time when a change needs to be made (see [here](https://github.com/Sefaria/Sefaria-Mobile/blob/c05a9566212ba58d1b0ada3b4b1ce2f513fd066b/InterruptingMessage.js#L68)). To remove the last remaining dependency of the old interrupting message code and ensure backwards compatibility with current mobile app users, there needs to be redirects to the new API endpoints. Having these redirects should work, because the fetch call in the mobile app should default to following redirects though it isn't explicitly specified. 

# Requirements (What I was trying to accomplish)
* https://www.sefaria.org/static/mobile/message-en.json needs to redirect to https://credible-basketball-a14e66cd27.strapiapp.com/api/mobile-message
* https://www.sefaria.org/static/mobile/message-he.json needs to redirect to https://credible-basketball-a14e66cd27.strapiapp.com/api/mobile-message-he

## Further considerations
In the future, the mobile app's URLs for the endpoints will be changed to use the new Strapi based ones, but those will be included in a new update.

## Conclusion
I need to have this done soon (likely by the end of this week), so I tried to get the ball rolling for you guys (@edamboritz and @BrendanGalloway) even though I have no idea what I'm doing  :)

2023-09-19 08:13 UTC, BrendanGalloway requested changes
The static json file is being moved out of the versioning system to an external location.  Is there any synchronisity between the contents of the json file and the version of the mobile/main site?  How are updates to the json file captured, reviewed and deployed?

2023-09-19 08:13 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/rollout/nginx.yaml
> +            value: "{{ .Values.localSettings.STRAPI_LOCATION }}"
This needs 
1) For .Values.localSettings.STRAPI_LOCATION to be defined in the values.yaml file of the chart.  You can populate with a sensible default if all Sefaria environments will redirect to the same endpoint
2) per-environment values to populated in the environment values files - build/ci/production-values.yaml for prod, build/ci/sandbox-values.yaml for per-commit tests, build/ci/integration-values.yaml for integration tests and create-cauldron.sh in the cauldrons repo for cauldrons.

2023-09-19 14:33 UTC, BrendanGalloway approved these changes

2023-09-20 21:06 UTC, relyks commented
Tested it on the mobile app using the cauldron URL and it worked.

2023-09-20 21:07 UTC, merged

2023-09-20 21:07 UTC, relyks commented
Tested it on the mobile app using the cauldron URL and it worked