Elasticsearch 8 compat
Sefaria/Sefaria-Project pull request #1644
Opened 2023-09-20 07:31 UTC by nsantacruz

Branch that enables compatibility with Elasticsearch 8 while still maintaining compatibility with Elasticsearch 6.

2023-11-28 12:35 UTC, BrendanGalloway requested changes

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/cronjob/reindex-elasticsearch-es6.yaml
> +                name: {{ template "sefaria.secrets.elasticAdmin" . }}
if this isn't needed in ES6, can remove ref?

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/cronjob/reindex-elasticsearch-es6.yaml
> +              value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
Addd SEARCH_HOST override to point to ES6 server

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/rollout/nginx.yaml
>              value: "{{ .Values.nginx.SEARCH_HOST }}"
needs a envFrom with the elastic user and password

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/values.yaml
> +    #   SEARCH_URL
ES6_SEARCH_HOST: 
ES8_SEARCH_HOST:

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/cronjob/reindex-elasticsearch-es6.yaml
> +{{- if .Values.cronJobs.reindexElasticSearch.enabled }}
maybe set the to cronjobs.reindexElasticSearch6 and  cronjobs.reindexElasticSearch8

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/values.yaml
> +    #   SEARCH_URL
Maybe add in cronjob.reindexelasticsearch.x

2023-11-28 12:35 UTC, BrendanGalloway commented on helm-chart/sefaria-project/templates/cronjob/reindex-elasticsearch-es6.yaml
> +              value: "varnish-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
name: SEARCH_HOST
values: {{ .Values.cronjobs.reindexelasticsearch.ES6 }}

2023-11-28 13:08 UTC, BrendanGalloway submitted a review, later dismissed

2023-12-05 08:50 UTC, edamboritz approved these changes

2023-12-05 08:53 UTC, merged