Banners don't jumble up the mobile navigation menu anymore!
Sefaria/Sefaria-Project pull request #1679
Opened 2023-10-26 17:02 UTC by relyks

A simple property change was made to ensure the navigation menu on mobile web is displayed properly when a banner is displayed.

In collaboration with @yonadavGit :)

2023-10-29 08:28 UTC, edamboritz requested changes
I'm not sure this solves the issue. Looking at some static pages (about, team etc) this fix actually doesnt allow the menu to show at all. 

Is there a fix we can do on the css of the banner, rather than the menu that can fix this?

2023-10-29 14:44 UTC, edamboritz commented
I've added two commits: 
The first fixes the issue where the `position:absolute`d nav manu would not have height because percentage of the containing ekement became meaningless, so changing to vh (viewport height units) fixed. 
The second is a fix that would not work for Firefox until later this year but seemed better to me in terms of maintaining the original intent - adding special css with the :has psuedo class that can target the nav menu if the banner element is present beofre it, and adds its height to the height and offest calculations done for the nav menu

2023-10-29 18:49 UTC, nsantacruz submitted a review, later dismissed

2023-10-30 07:07 UTC, edamboritz approved these changes

2023-10-30 08:37 UTC, nsantacruz approved these changes

2023-10-30 09:08 UTC, merged