Hopefully, the last time to update team members manually
Sefaria/Sefaria-Project pull request #1707
Opened 2023-11-10 19:33 UTC by relyks

Update titles for Shanee, Olivia and add Yedida. This should be the last time someone will have to update the static content of the English and Hebrew team pages before the Strapi CMS rollout

2023-11-10 19:40 UTC, shaneerosen requested changes
Check the hebrew pronouns.

2023-11-12 13:31 UTC, edamboritz commented on templates/static/he/team.html
> +                                <span class="int-he">מהנדסת תוכנה בכירה וראש תחום דאטה</span>
ניתוח נתונים 
over 
דאטה

2023-11-13 16:08 UTC, edamboritz approved these changes

2023-11-13 19:40 UTC, shaneerosen approved these changes

2023-11-13 20:16 UTC, merged