Add a new redirect for tracking donations from Munich promotional presentation
Sefaria/Sefaria-Project pull request #1763
Opened 2024-01-03 05:05 UTC by relyks

@EliezerIsrael is presenting at a talk in Munich and would like to provide a shortened user-friendly URL to facilitate donations (`sefaria.org/give`). The URL provided has a `mu` GET parameter to track the campaign. 

### Future considerations
If this becomes a regular request to have other user-friendly links that redirect to specific campaigns, a separate utility or admin panel plugin should be created to save desirable URL paths and their counterpart donation URLs to the database. A URL handler could check if there are any special donation paths available. However, caching for those URLs would be necessary to prevent slow URL resolution from making a call to the database on every request.

2024-01-03 08:04 UTC, EliezerIsrael commented
@relyks I think we should add a generic redirect like sefaria.org/give/X , where X is any campaign ID, that redirects to https://donate.sefaria.org/give/550774/#!/donation/checkout?c_src=X.  That would be more future-proof, and excuse us from doing one-off redirects.

2024-01-03 08:05 UTC, EliezerIsrael requested changes
@relyks I think we should add a generic redirect like sefaria.org/give/X , where X is any campaign ID, that redirects to https://donate.sefaria.org/give/550774/#!/donation/checkout?c_src=X. That would be more future-proof, and excuse us from doing one-off redirects.

2024-01-03 23:05 UTC, relyks commented
> @relyks I think we should add a generic redirect like sefaria.org/give/X , where X is any campaign ID, that redirects to https://donate.sefaria.org/give/550774/#!/donation/checkout?c_src=X. That would be more future-proof, and excuse us from doing one-off redirects.

I agree. I implemented what you suggested :+1:

2024-01-09 14:03 UTC, edamboritz approved these changes

2024-01-09 14:03 UTC, merged