Validate interface language is sticky when source language changes
Sefaria/Sefaria-Project pull request #1973
Opened 2024-07-18 18:33 UTC by b-w-cole

## Description
Tests the following:
**Hebrew/English Language**
* English source
* Bilingual source
* Hebrew source

resulting in 6 tests

## Code Changes
_The following changes were made to the files below_

## Notes
_Any additional notes go here_

2024-07-18 18:34 UTC, b-w-cole commented
Related to https://github.com/Sefaria/Sefaria-Playwright-Tests/issues/19

2024-07-24 08:17 UTC, saengel requested changes
Hi @b-w-cole - overall looks fantastic, thank you for writing these!

A suggestion - since the overall pattern of each test is repetitive, what do you think about trying to use test parameterize?

Here's the playwright docs: https://playwright.dev/docs/test-parameterize

Let me know what you think, and thanks again.

2024-07-24 18:08 UTC, b-w-cole commented
Hi @saengel , sure I will give that a try.  Please expect another draft in a day or two.  Thanks for the feedback!

2024-07-24 21:10 UTC, b-w-cole commented
Well that condensed things considerably!  Let me know :)

2024-07-25 10:52 UTC, saengel requested changes
Fantastic!

One small ask - can we reformat the parameterized array so it's a bit more readable? 

Then we should be good to go!

2024-07-25 16:47 UTC, b-w-cole commented
@saengel , sure thing!  Completed.

2024-07-25 16:49 UTC, saengel approved these changes
Looks great, thank you!

2024-08-10 00:17 UTC, b-w-cole commented
Please see https://github.com/Sefaria/Sefaria-Project/pull/1979/files for an updated version of this test, with new global vars and an additional function in utils, making source text language changes easier.

2025-01-15 12:12 UTC, merged