Feature/sc 27331/new sidebar component2
Sefaria/Sefaria-Project pull request #2163
Opened 2024-12-10 10:20 UTC by stevekaplan123

## Description
The core of this PR is the SheetContentSidebar component which is used by the Sheets Viewer and will eventually be used by the Sheets Editor as well.  It displays profile information, a profile picture, a follow button, and a list of the sheet maker's collections that the sheet is in.

## Code Changes
The SheetContentSidebar works by loading the profile data through Sefaria.profileAPI and then passing the profile object to a new component SheetProfileInfo, which uses the profile data to display the user's education, location, organization, and followers information.  A new component PartOfCollections displays the collections that the sheet maker put the sheet in.

2024-12-15 11:16 UTC, yitzhakc requested changes

2024-12-15 15:01 UTC, stevekaplan123 commented on static/js/sheets/SheetContent.jsx
> +class SheetNotice extends Component {
It seems to have never been used....

2025-01-06 12:29 UTC, saengel approved these changes
Looks great! Pulled locally as well :)

Left some small nitpicky comments, but they really aren't a huge deal.

2025-01-06 12:29 UTC, saengel commented on static/js/sheets/Sheet.jsx
> +import {SheetContent} from "./SheetContent";
I believe it's best practice for the imports to have a space between the curly brace and the name, ie `{ SheetContent }`.

2025-01-06 12:29 UTC, saengel commented on static/js/sheets/SheetContentSidebar.jsx
> +import {FollowButton, InterfaceText} from "../Misc";
Same comment here regarding spacing imports.

2025-01-06 12:29 UTC, saengel commented on static/js/sheets/SheetContentSidebar.jsx
> +        Sefaria.profileAPI(authorUrl.replace("/profile/", "")).then(profile => {
We're going to need to update this to say `.replace("/sheets/profile/", ""))` likely after https://github.com/Sefaria/Sefaria-Project/pull/2204 is merged.

2025-01-06 12:29 UTC, saengel commented on static/js/UserProfile.jsx
> +export {UserProfile, UserBackground};
Also, do these need spaces?

2025-01-06 12:29 UTC, saengel commented on static/js/ReaderPanel.jsx
> +import {UserProfile}  from './UserProfile';
Same comment regarding spacing with the `{ }`.

2025-01-12 10:12 UTC, stevekaplan123 commented on static/js/sheets/SheetContentSidebar.jsx
> +        Sefaria.profileAPI(authorUrl.replace("/profile/", "")).then(profile => {
I'm going to leave it for now because I suspect after that PR's merged we'll have to change a lot of links to read "/sheets/..."  Is there a card to remind us to do this?

2025-01-12 10:56 UTC, saengel commented on static/js/sheets/SheetContentSidebar.jsx
> +        Sefaria.profileAPI(authorUrl.replace("/profile/", "")).then(profile => {
Actually, @YishaiGlasner already completed this work for the `profile`. So it would help if you could change this instance as well. We'll obviously still have to comb through it all later, but for now it would help :)

2025-01-13 13:32 UTC, merged