Feature/sc 27328/options popover component2
Sefaria/Sefaria-Project pull request #2172
Opened 2024-12-11 13:23 UTC by stevekaplan123

## Description
The 'options popover component' is a menu providing sheet viewers with the ability to save/remove the sheet (saved texts and sheets can be seen at /texts/saved), make a copy of the sheet, export the sheet to google docs, add the sheet to a collection, or share the sheet.  Most of this functionality used to exist in AboutSheet.jsx which would show in the Connections Panel.  It is now possible to open a dropdown menu and choose one of these options from the main panel of the sheets viewer.  Depending on what option was chosen, the user is then shown a modal either showing the status of the action chosen or allowing the user to choose what to do next.  For example, if the user copies the sheet, they will see a modal that says "Copying..." and once copied, will show a link to the copied sheet.  Exporting to google docs and saving the sheet is similar and show the status of the exported/saved sheet.  On the other hand, for adding to a collection, the user is presented with a modal allowing them to choose what collection(s) to add the sheet to, and allowing them to create a new collection.  Likewise, for sharing the sheet, the user is presented with a modal allowing them to choose different ways of sharing the sheet (through different social media). 

## Code Changes
The core of the code for this set of features is in SheetOptions.jsx, which has two stages: (1) First, the user clicks on an ellipse to show a DropdownMenu with all of the options listed above.  (2) Second, a modal appears showing the status of the action chosen or a menu, making heavy usage of a few new generic components, such as Modal and GenericSheetModal.  The Modal I placed in the /common directory while the GenericSheetModal I implemented in SheetOptions.  I had to make a few relatively minor changes to DropdownMenu to be able to pass down callback functions, for example.  I also modified the generic sefaria.js apiRequestWithBody so that I could handle the errors directly instead of apiRequestWithBody handling the errors for me.  This was necessary to implement Google Export as the API generates a 401 authentication error if the user hasn't setup their gauth credentials with Sefaria.

2025-01-06 13:00 UTC, saengel requested changes
Overall looks great, and everything worked wonderfully locally!

Most of the comments are very very very minor and nitpicky comments about spacing to improve code readability. It could very well be we have different conventions, in which case feel free to ignore!

One thing that goes beyond that though is just a question about the default lorem ipsum text passed into `DropdownMenuItemWithIcon`. I'm wondering if we should reverse the logic of that / discuss more together, otherwise it could interfere with some pre-existing implementations.

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/Sheet.jsx
> +import {SheetOptions} from "./SheetOptions";
Spacing :)

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetContent.jsx
> +          <SheetMetaDataBox authorStatement={this.props.authorStatement} authorUrl={this.props.authorUrl}
To enhance readability, would you consider reformatting like this:

```
 <SheetMetaDataBox authorStatement={this.props.authorStatement} 
                      authorUrl={this.props.authorUrl}
                      authorImage={this.props.authorImage} 
                      title={this.props.title}
                      summary={this.props.summary}
                      sheetOptions={this.props.sheetOptions}/>
```

(i.e. each prop aligned on a new line - hard to get exactly right in markdown)

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +import {DropdownMenu, DropdownMenuItem, DropdownMenuItemWithIcon} from "../common/DropdownMenu";
Same spacing thoughts :) (but maybe our convention is different?)

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +export {SheetOptions};
New line at the end of the file.

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +const getExportingStatus = () => {
New line before new function?

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +  // `editable` -- whether the sheet belongs to the current user
This is a very helpful comment! Thank you!

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +  useEffect(() => {
A new line before useEffect would be helpful

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +  const getSignUpModalKind = () => {
A new ling before `getSignUpModalKind` would be helpful

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +              descEn={""}
The use of `descEn` and `descHe` in these cases makes me think we really should have the default values be empty, and online pass lorem ipsum as needed. Curious what you think....

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +const CollectionsButton = ({setCollectionsMode, editable}) => {
New line before `CollectionsButton`

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +const ShareModal = ({sheetID, close}) => {
New line before `ShareModal`

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +const CollectionsModal = ({close, sheetID}) => {
New line before `CollectionsModal`

2025-01-06 13:00 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +const CopyModal = ({close, sheetID}) => {
New line before `CopyModal`

2025-01-12 09:51 UTC, stevekaplan123 commented on static/js/sheets/SheetOptions.jsx
> +              descEn={""}
I agree.  I just left it that way as that was how it was originally.

2025-01-12 09:54 UTC, stevekaplan123 commented on static/js/common/modal.jsx
> +export default Modal;
Why does it need a new line?

2025-01-12 09:55 UTC, stevekaplan123 commented on static/css/s2.css
> +.overlayDialogModal {
We don't currently seem to be consistent in s2.css.  Does it really enhance readability that much?

2025-01-12 09:58 UTC, stevekaplan123 commented on static/js/sheets/SheetOptions.jsx
> +    delete newSheet.id;
It's legacy code.  I didn't write this function.  But what do you see as the risks?  In case 'id' isn't there?  If it's not there, there's no error.

2025-01-12 10:05 UTC, stevekaplan123 commented on static/js/sheets/SheetOptions.jsx
> +    return <><InterfaceText>Success!</InterfaceText>&nbsp;
Good point.  Probably should be CSS thanks.

2025-01-12 10:06 UTC, stevekaplan123 commented on static/js/common/DropdownMenu.jsx
>  const DropdownMenuItem = ({url, children, newTab}) => {
This branch hasn't had modularization-main merged in in a while.  Going to do that now...!

2025-01-12 10:53 UTC, saengel commented on static/css/s2.css
> +.overlayDialogModal {
A little, but if it's not consistent within the file, don't worry about it :)

2025-01-12 10:53 UTC, saengel commented on static/js/common/DropdownMenu.jsx
>  const DropdownMenuItem = ({url, children, newTab}) => {
Okay great, thanks!

2025-01-12 10:54 UTC, saengel commented on static/js/sheets/SheetOptions.jsx
> +    delete newSheet.id;
Okay got it, I thought you added it.

2025-01-12 10:55 UTC, saengel commented on static/js/common/modal.jsx
> +export default Modal;
Generally it's considered best practice in terms of style and readability (see: https://eslint.style/rules/js/eol-last).

2025-01-13 11:08 UTC, yitzhakc approved these changes

2025-01-13 12:24 UTC, saengel approved these changes

2025-01-13 13:12 UTC, merged