new moderator tools for removing links
Sefaria/Sefaria-Project pull request #2174
Opened 2024-12-11 14:01 UTC by YishaiGlasner

## Description
new moderator tools for removing links

## Code Changes

- new helper function remove_links_from_csv in link.py
- add option to use this function in links_upload_api, when the request has `'action': 'DELETE'`
- new component for removing links in modtools

2024-12-22 19:01 UTC, yitzhakc requested changes

2024-12-23 07:06 UTC, YishaiGlasner commented on static/js/ModeratorToolsPanel.jsx
> +                    Please note that it should be the exact ref, so 'Genesis 1' is different than 'Genesis 1:1-31'
the instruction are for very few people. i think that the requester feedback is better here

2024-12-23 07:10 UTC, YishaiGlasner commented on sefaria/helper/link.py
> +            print(e, refs)
it was for debugging and forgotten there

2024-12-23 07:17 UTC, YishaiGlasner commented on sefaria/views.py
> +        return jsonResponse({"status": "ok", "data": func(*args)})
i'm not sure what you mean here. if the try statement fails we return HttpResponseBadRequest. if it succeeds, it means the csv file is ok, so the general status is ok. now, the user wants to know how many links were handled successfully and which links failed and why, so we send this information to the client in a csv file.

2024-12-24 08:27 UTC, yitzhakc commented on sefaria/views.py
> +        return jsonResponse({"status": "ok", "data": func(*args)})
Ah, you're correct, I mis-read the code. Thanks for pointing that out!

2024-12-24 09:45 UTC, merged