Remove sheets from Torah Tracker
Sefaria/Sefaria-Project pull request #2176
Opened 2024-12-11 17:39 UTC by saengel

## Description
This PR removes the sheets stats from the Torah Tracker. 

## Code Changes
1. `static/js/UserStats.jsx` - Remove all references to sheets, underlying functions, and implementations. 

## Notes
- A chance we may be incorporating other data where sheets was.

2024-12-22 08:36 UTC, yitzhakc requested changes

2024-12-22 08:36 UTC, yitzhakc commented on static/js/UserStats.jsx
> +        console.log('user_data', user_data);
Remove console log

2024-12-22 18:57 UTC, saengel commented on static/js/UserStats.jsx
> +        console.log('user_data', user_data);
Good catch! Done.

2024-12-24 09:45 UTC, yitzhakc approved these changes

2024-12-24 10:44 UTC, merged