Feature/sc 27825/add to sheet2
Sefaria/Sefaria-Project pull request #2179
Opened 2024-12-12 07:53 UTC by stevekaplan123

## Description
The feature this PR implements is that it attaches an "Add to Sheet" button to every segment of the sheet.  The button is hidden, but when the user clicks on the segment, the "Add to Sheet" button appears.  After the user clicks the "Add to Sheet" button, a modal appears allowing the user to select which of the user's sheets to add the segment to.  

## Code Changes
1. I inherited 100 lines of code in Sheet.jsx (pre-modularization) that renders the sheet segments.  At one point in this project, I moved them into their own function getSources().   However, in this PR, I needed to modify this function in order to render an "Add to Sheet" button inside each segment, and so I took the opportunity to re-factor getSources() so that it is now a 20 line function.  I also moved the segment components from SheetContent.jsx to SheetContentSegments.jsx, although I simply copied and pasted and so git lost track of the relevant commits.  I added a component AddToSheetButton in SheetContent.jsx that I pass down to each of the sheet segment components in SheetContentSegments.
2. As the other modals (CopyModal, SaveModal, GoogleExportModal, etc.) are present in SheetOptions.jsx, I put the AddToSourceSheetModal in SheetOptions.jsx.  This is questionable.  Perhaps it should be in SheetContent.jsx as it is not triggered by the dropdown menu in SheetOptions.jsx.  In any case, AddToSourceSheetModal simply wraps a previously existing component AddToSourceSheetBox with a Modal component.  I had to slightly modify AddToSourceSheetBox to not show the google doc advertisement.

2025-01-08 10:10 UTC, yitzhakc requested changes

2025-01-08 13:28 UTC, stevekaplan123 commented on static/js/sheets/SheetContent.jsx
> +        key={i}
thanks for pointing this out.  I did not know about this...

2025-01-08 13:51 UTC, stevekaplan123 commented on static/js/sheets/SheetContentSegments.jsx
> +          onKeyPress={function(e) {
I added a prop handleKeyPress to deal with this case

2025-01-09 10:17 UTC, YishaiGlasner commented on static/js/sheets/SheetContent.jsx
> +      const { highlightedNode, sheetSourceClick } = this.props;
why is this in the loop and not at the top in line 109?

2025-01-09 10:17 UTC, YishaiGlasner commented on static/js/sheets/SheetContent.jsx
> +      let highlighted = source.node === this.props.highlightedNode;
use highlightedNode without this.props

2025-01-09 10:17 UTC, YishaiGlasner commented on static/js/sheets/SheetContent.jsx
> +        const highlightedRef = this.props.highlightedRefsInSheet ? Sefaria.normRefList(this.props.highlightedRefsInSheet) : null;
you can use &&

2025-01-09 10:17 UTC, YishaiGlasner commented on static/js/sheets/SheetContent.jsx
> +        highlighted = highlightedNode ? highlightedNode === source.node : highlightedRef ? Sefaria.refContains(source.ref, highlightedRef) : false;
this is dufficult to follow

2025-01-09 10:17 UTC, YishaiGlasner commented on static/js/sheets/SheetContent.jsx
> +        <AddToSourceSheetModal nodeRef={nodeRef} srefs={highlightedRefs} close={() => setShowingModal(false)}/>}
i'm not sure about our policy but defining function (as other not simple variabales) can cause unnecessary re-renders

2025-01-09 10:17 UTC, YishaiGlasner commented on static/js/sheets/SheetContentSegments.jsx
> +}
are there any changes here or it's just pasted? (i didn't review)

2025-01-12 10:15 UTC, stevekaplan123 commented on static/js/sheets/SheetContentSegments.jsx
> +}
Just pasted from SheetContent.jsx

2025-01-12 10:33 UTC, stevekaplan123 commented on static/js/sheets/SheetContent.jsx
> +      const { highlightedNode, sheetSourceClick } = this.props;
Good point... moving it

2025-01-19 10:37 UTC, yitzhakc requested changes

2025-01-20 12:15 UTC, YishaiGlasner commented on static/css/s2.css
> +	display: inline-flex;
indentation

2025-01-20 12:15 UTC, YishaiGlasner commented on static/css/s2.css
> +	background-color: var(--midrash-green);
are we doing a sheets-green var like we said?
another thought - i don't really know modularization, but i guess that we have some shared components that should be blue in texts and green in sheets.
if so we can do something like
```
:root {
  --sefaria-texts-color: var(--sefaria-blue)
  --sefaria-sheets-color: <#...>
}
.texts {
  --brand-color: var(--sefaria-texts-color)
}
.sheets {
  --brand-color: var(--sefaria-sheets-color)
}
```
and then we can use brand-color anywhere
@edamboritz what do you think?

2025-01-20 13:36 UTC, yitzhakc commented on static/css/s2.css
> +	background-color: var(--midrash-green);
That is the plan; but the implementation will happen down the line.

2025-01-20 13:42 UTC, yitzhakc approved these changes

2025-01-21 08:00 UTC, merged