[Sheets] Saved, History and Notes
Sefaria/Sefaria-Project pull request #2203
Opened 2024-12-23 17:26 UTC by saengel

## Description
Creating the "sheets" side of Saved, History and Notes. 

## Code Changes
1. `reader/views.py` - Shift `page` to match the expanded `menuOpen` options (`texts-saved`, `sheets-saved`, `texts-history`, `sheets-history`, `notes`). 
2. `sefaria/urls.py` - Add new URLs for sheets
3. `static/js/ReaderApp.jsx` - URL changes and handling on the FE
4. `static/js/ReaderPanel.jsx` - Using sheets and library wrapper classes
5.  `static/js/UserHistoryPanel.jsx` - Bulk of changes: (a) defining wrapper components with `dataSource` prop, adjusting `UserHistoryPanel` and `UserHistoryList` to filter contents based on "mode" (i.e. only display saved _sheets_ in sheets mode, and only saved _refs_ in library mode). 

## Notes
There are two known bugs that still need to be resolved, why this is a draft PR. Bugs are detailed on card.

2025-01-08 10:02 UTC, yitzhakc requested changes

2025-01-08 10:02 UTC, yitzhakc commented on static/js/UserHistoryPanel.jsx
> +      const filteredData = data.filter(item => {
Let's try and unify the filtering on the underlying data source that happens here  and in lines 75-76, so we have a single implementation of the filtering.
(I wrote additional comments in parentheses, that might be moot once the filtering is unified)

2025-01-08 10:02 UTC, yitzhakc commented on static/js/UserHistoryPanel.jsx
> +        if (menuOpen === "sheets-saved" || menuOpen === "sheets-history") {
(Would it be simpler to check the `dataSource` here, versus checking menuOpen states?)

2025-01-08 10:21 UTC, saengel commented on static/js/UserHistoryPanel.jsx
> +  if ((menuOpen === 'texts-history' || menuOpen === "sheets-history") && !Sefaria.is_history_enabled) {
Absolutely! Thanks for catching! Do you have a preference?

2025-01-08 10:22 UTC, saengel commented on static/js/UserHistoryPanel.jsx
> +// TODO - Wrapper pass data-source to conditionally set menuOpen, to make sure component switches with tabs.
Thanks for catching!

2025-01-08 10:50 UTC, saengel commented on static/js/UserHistoryPanel.jsx
> +      const filteredData = data.filter(item => {
As discussed, extract logic to a function?

2025-01-12 08:58 UTC, saengel commented on static/js/UserHistoryPanel.jsx
> +        return true; // Default: No filtering
I don't think it was necessary at all, and just removed. Seems to be working fine.  Thanks for catching!

2025-01-12 09:05 UTC, saengel commented on static/js/UserHistoryPanel.jsx
> +  if ((menuOpen === 'texts-history' || menuOpen === "sheets-history") && !Sefaria.is_history_enabled) {
I went with single quotes, please let me know if there's a preference for double.

2025-01-13 11:18 UTC, yitzhakc approved these changes

2025-01-13 12:18 UTC, yitzhakc approved these changes

2025-01-13 12:19 UTC, merged